[package]
name = "reach-cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "reach"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.28", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.11", features = ["json"] }
serde_json = "1.0"
roxmltree = "0.19.0"
colored = "3.0.0"
