# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "src/schema.rs"
schema = "rchat"
custom_type_derives = ["diesel::query_builder::QueryId", "Clone"]

[migrations_directory]
dir = "C:\\Users\\98107\\desktop\\zfyre\\rustprojects\\reach-cli\\reach\\src\\rchat\\migrations"
