[package]
name = "reachdb"
version = "0.1.0"
edition = "2024"

[dependencies]
memmap2 = "0.9.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bincode = "1.3.3"
tempfile = "3.17.1"
rand = "0.8"
sled = "0.34.7"
log = "0.4.26"
env_logger = "0.11.6"