[package]
name = "reachtui"
version = "0.1.0"
edition = "2024"

[dependencies]
reachapi = { path = "../reachapi" }
metadata = { path = "../metadata" }
termimad = "0.31.2"
ratatui = "0.24.0"
crossterm = "0.27.0"