[package]
name = "reachapi"
version = "0.1.0"
edition = "2024"

[features]
requires_config = []

[dependencies]
roxmltree = "0.19.0"
serde_json = "1.0"
reqwest = { version = "0.11", features = ["json"] }
clap = { version = "4.5.28", features = ["derive"] }